name: app_store_metadata
description: A comprehensive Dart SDK for fetching rich app metadata from Google Play Store and Apple App Store with complete iTunes API coverage
version: 2.1.0
homepage: https://github.com/DanhTran0312/app_store_metadata
repository: https://github.com/DanhTran0312/app_store_metadata
documentation: https://github.com/DanhTran0312/app_store_metadata

environment:
  sdk: ^3.8.1

dependencies:
  http: ^1.5.0
  html: ^0.15.6
  dart_mappable: ^4.6.0
  equatable: ^2.0.7

dev_dependencies:
  build_runner: ^2.7.0
  dart_mappable_builder: ^4.6.0
  lints: ^6.0.0
  test: ^1.26.3
